name: Sync Docs to Wiki

on:
  push:
    branches:
      - main  # Trigger when changes are pushed to the main branch

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clone Wiki Repository
        run: |
          git clone https://jakobsonsjanis:${{ secrets.GITHUB_TOKEN }}@github.com/jakobsonsjanis/github-pages-test.wiki.git wiki
      - name: Sync Docs
        run: |
          rsync -av --delete ./docs/ ./wiki/
          cd wiki
          git add .
          git commit -m "Sync content from /docs"
          git push
