name: Sync Docs to Wiki

on:
  push:
    branches:
      - main

jobs:
  sync-wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Clone Wiki Repository
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/jakobsonsjanis/github-pages-test.wiki.git wiki

      - name: Configure Git User
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Collect All /docs Folders
        run: |
          mkdir -p wiki/docs
          find . -type d -name "docs" -not -path "./wiki/*" | while read DOC_FOLDER; do
            rsync -av --exclude=".git" "$DOC_FOLDER/" wiki/docs/
          done

      - name: Commit and Push to Wiki
        run: |
          cd wiki
          git add .
          git commit -m "Sync all /docs content to Wiki"
          git push
